### ISSUE TITLE
one drive video links

### ISSUE THREAD

**Issue by PitchAbyss** [marcomontalbano/video-to-markdown#66]
why adding one drive links end up like this

![image](https://github.com/marcomontalbano/video-to-markdown/assets/13099434/f1c64445-e6e4-4937-b8ee-0ffd5547089d)

**Comment by marcomontalbano** [comment]
Hi @PitchAbyss , can you share a one drive link che is not working?

**Comment by PitchAbyss** [comment]
> Hi @PitchAbyss , can you share a one drive link che is not working?

hi sir i just checked i just uploaded a video on one drive and got the link and when i choose anyone with link can edit it changes the link to photo.saasc.dssw link i dnt know why one drive is doing it

any recommendation how to upload videos to one drive to get it working

**Comment by marcomontalbano** [comment]
Hi @PitchAbyss, thanks for highlighting this issue. I checked the problem you mentioned and noticed that OneDrive differs today from when I implemented this feature.

I just released a fix that should solve the problem. Can you double-check?

This is a sample link https://1drv.ms/v/s!An21T-lhvYKSkFrZiLdl_yvu42hI?e=Ie3z2S but you can try with yours.

**Comment by PitchAbyss** [comment]
> Hi @PitchAbyss, thanks for highlighting this issue. I checked the problem you mentioned and noticed that OneDrive differs today from when I implemented this feature.
> 
> I just released a fix that should solve the problem. Can you double-check?
> 
> This is a sample link https://1drv.ms/v/s!An21T-lhvYKSkFrZiLdl_yvu42hI?e=Ie3z2S but you can try with yours.

the link you shared works but please test these links too

https://1drv.ms/v/c/1c827834532d46a7/ETAjK46wOQhKvaNk-SzK5kMBvglqiXaAOVnbr7H2PhvvoA?e=Qblvlh

https://z12d3-my.sharepoint.com/:v:/g/personal/modderabyss_z12d3_onmicrosoft_com/EUiGPxF_zpRKvyIF6DvCZuUBCFLUTPbKUZOGRk3QJlgAfQ?e=Qb24G9

**Comment by marcomontalbano** [comment]
It looks like your share-link URL is different. From where did you get the first link? The second link is different also, it is a sharepoint, not a OneDrive one.

The link should be a public link from https://onedrive.live.com.

Here, is how I got the link from onedrive.live.com:

https://github.com/marcomontalbano/video-to-markdown/assets/1681269/c86a711e-7a1b-4ea6-ab64-63332e1477ce

**Comment by PitchAbyss** [comment]
> It looks like your share-link URL is different. From where did you get the first link? The second link is different also, it is a sharepoint, not a OneDrive one.
> 
> The link should be a public link from https://onedrive.live.com. Are you using another URL? Do you have a paid subscription?
> 
> Here, is how I got the link from onedrive.live.com:
> 
>  copy-link-from-onedrive.mp4

here is the test link i got from one drive it still doesnt work i dnt know why ...yes on share point i have a dev account

https://github.com/marcomontalbano/video-to-markdown/assets/13099434/5a95ed2f-80ac-4bb0-8fca-ac29d68942ce

**Comment by marcomontalbano** [comment]
Thanks a lot for the reproduction. It's tough understanding why UI and generated links are different. Even the API authentication is different between the two links :disappointed:.

Can you share another video link, so that I'll have two links to double check. I'll try to fix it :+1:

**Comment by marcomontalbano** [comment]
When I open the first link (https://1drv.ms/v/c/1c827834532d46a7/EZgTHy334BlEqtrXfXr7h8oBaEwQ4smTn_szzgtp2Ih73w)  in Chrome I'm redirected to the microsoft login page. On other browsers I see a black screen with audio only. Is it public? Can you double-check?

For the second link, sharepoint is not yet supported. You can open a separate feature request for it. Please attach the two links to the request.

**Comment by PitchAbyss** [comment]
> When I open the first link (https://1drv.ms/v/c/1c827834532d46a7/EZgTHy334BlEqtrXfXr7h8oBaEwQ4smTn_szzgtp2Ih73w) in Chrome I'm redirected to the microsoft login page. On other browsers I see a black screen with audio only. Is it public? Can you double-check?
> 
> For the second link, sharepoint is not yet supported. You can open a separate feature request for it. Please attach the two links to the request.

so sorry about the link i dnt know why android app created this faulty link please check this one

https://1drv.ms/v/c/1c827834532d46a7/EQFnKXI0JuJDgvpfJl0ISsABeWzhbuDSjeU2Y5LJzQ4oCA?e=y0r6md

**Comment by marcomontalbano** [comment]
I just released a new version that support this link format. Let me know if everything is working now :crossed_fingers:

**Comment by PitchAbyss** [comment]
> I just released a new version that support this link format. Let me know if everything is working now 🤞

awesome the one drive personal links are working now leaves just 2 more requests thanks alot dev
